# M12-L1 Problem 2

Sometimes the dimensionality is greater than the number of samples. For example,in this problem X has 19 features, but there are only 4 data points. You will need to use the alternate PCA formulation in this case. Follow the steps in the cells below to implement this method.

In [145]:
import numpy as np
import matplotlib.pyplot as plt

X = np.array([  [-2,  1,  2, -3,  4,  1,  0,  3,  0,  2,  1,  1,  2,  3, -2, -3, 2,  1,  0],
                [ 1,  2, -4,  2, -4,  2,  5,  2,  2,  1, -3,  0,  0,  1, -2,  1, 1, -3, -2],
                [ 1, -3,  2,  1,  0, -3, -5, -1,  3,  3, -2, -3, -2, -1,  1,  0, 5,  4,  2],
                [ 3, -1,  0,  2,  2, -5, -4, -1,  2, -1,  3,  4,  4,  2,  1,  2, -2,  1, -1]])


## Computing Principal Components

### The A matrix

First, you should compute the `A` matrix, where A is $(X-\mu)'$. (Note the transpose)

Print this matrix below. It should have size $19\times 4$.

In [146]:
# YOUR CODE GOES HERE
mu = np.mean(X, axis=1)
A = (X - mu[:, np.newaxis]).T
print("A = \n", A)

A = 
 [[-2.68421053  0.89473684  0.89473684  2.42105263]
 [ 0.31578947  1.89473684 -3.10526316 -1.57894737]
 [ 1.31578947 -4.10526316  1.89473684 -0.57894737]
 [-3.68421053  1.89473684  0.89473684  1.42105263]
 [ 3.31578947 -4.10526316 -0.10526316  1.42105263]
 [ 0.31578947  1.89473684 -3.10526316 -5.57894737]
 [-0.68421053  4.89473684 -5.10526316 -4.57894737]
 [ 2.31578947  1.89473684 -1.10526316 -1.57894737]
 [-0.68421053  1.89473684  2.89473684  1.42105263]
 [ 1.31578947  0.89473684  2.89473684 -1.57894737]
 [ 0.31578947 -3.10526316 -2.10526316  2.42105263]
 [ 0.31578947 -0.10526316 -3.10526316  3.42105263]
 [ 1.31578947 -0.10526316 -2.10526316  3.42105263]
 [ 2.31578947  0.89473684 -1.10526316  1.42105263]
 [-2.68421053 -2.10526316  0.89473684  0.42105263]
 [-3.68421053  0.89473684 -0.10526316  1.42105263]
 [ 1.31578947  0.89473684  4.89473684 -2.57894737]
 [ 0.31578947 -3.10526316  3.89473684  0.42105263]
 [-0.68421053 -2.10526316  1.89473684 -1.57894737]]


### "Small" covariance matrix

By transposing $X-\mu$ to get $A$, now we can compute a smaller covariance matrix with $A' A$. Compute this matrix, `C`, below and print the result.

In [147]:
# YOUR CODE GOES HERE
# C = A @ A.T / (A.shape[0] - 1)
C = np.cov(A, rowvar=False)
print("C = \n", C)

C = 
 [[ 4.00584795 -1.1871345  -0.29824561 -0.69590643]
 [-1.1871345   5.98830409 -2.4005848  -2.39766082]
 [-0.29824561 -2.4005848   7.32163743  0.60233918]
 [-0.69590643 -2.39766082  0.60233918  6.36842105]]


### Finding nonzero eigenvectors
Next, find the useful (nonzero) eigenvectors of `C`. 

For validation purposes, there should be 3 useful eigenvectors, and the first one is `[-0.06628148 -0.79038331 0.47285044 0.38381435]`. 

Keep these eigenvectors in a $4\times 3$ array `e`.

In [148]:
# YOUR CODE GOES HERE
# compute eigenvectors of C [4 by 3 array]
e, V = np.linalg.eig(C)
print("Eigenvalues, e:\n", e)
print("Eigenvectors, e:\n", V)

Eigenvalues, e:
 [ 2.16813794 10.23121124  5.03784186  6.24701948]
Eigenvectors, e:
 [[-0.60379648 -0.03681195  0.79255238 -0.07704163]
 [-0.62182325  0.62756313 -0.45531269 -0.11041157]
 [-0.27604586 -0.61306499 -0.30436943 -0.67476607]
 [-0.41540863 -0.4784984  -0.26816101  0.72564773]]


### Calculating "eigenfaces"

Now, we have all we need to compute `U`, the matrix of eigenfaces.

$\bf{U}_i = \bf{A} \bf{e}_i$  

$(19 \times 3) = (19 \times 4)(4 \times 3)$

Compute and print U. Be sure to normalize your eigenvectors `e` before using the above equation.

In [149]:
# YOUR CODE GOES HERE
e_norm = np.linalg.norm(e, axis=0)
U = A @ e_norm
print("Eigenfaces, U:\n",U)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

## Projecting data into 3D

Now project your data into 3 dimensions with the formula: 

$\Omega = U^\text{T} A $  

$(3 \times 4) = (3 \times 19)(19 \times 4)$

Call the projected data $\Omega$ "`W`". Print `W.T`

In [ ]:
# YOUR CODE GOES HERE
W = U.T @ A
print('Projected data in 3 dimensions:\n',W.T)

Projected data in 3 dimensions:
 [3.28421053e+01 5.26315789e-02 9.40526316e+01 6.97894737e+01]


## Reconstructing data in 19-D

We can project the transformed data `W` back into the original 19-D space using:

$\Gamma_f = U \Omega + \Psi$   
where:  
$\Gamma_f = $ reconstructed data  
$U = $ eigenfaces  
$\Omega = $ Reduced data  
$\Psi = $ Means  

Do this, and compute the MSE between each reconstructed sample and corresponding original points. Report all 4 MSE values.




In [ ]:
# YOUR CODE GOES HERE
for i in range(4):
    X_reconstructed = U @ W[:,i] + mu
    MSE = np.mean((X - X_reconstructed[:, np.newaxis])**2)
    print("MSE for sample %d: %e" %(i+1,MSE[i]))

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

## 2-D Reconstruction


What if we had only used the first 2 eigenvectors to compute the eigenfaces?
Below, redo the earlier calculations, but use only two eigenfaces. Compute the 4 MSE values that you would get in this case.

(You should get an MSE of 3.626 for the first sample.)

In [ ]:
# YOUR CODE GOES HERE
print("Using only 2 eigenvectors:")
for i in range(4):
    X_reconstructed = U[:,:2] @ W[:2,i] + mu
    MSE2 = np.mean((X - X_reconstructed[:, np.newaxis])**2)
    print("MSE for sample %d: %e" %(i+1,MSE2[i]))